---
title: "Donloading Hate Speech Lexicon from hatebase.org"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
# Packages
library("httr") # API calls
library("jsonlite") # Extracting content from Hatebase repo
library("tidyverse") # Several data processing packages
library("data.table") # Convert list to data frame
```

# Authentication phase: Retrieving token 

```{r}
# Function args
version = "4-3" # current version as of Aug. 2019
api_key = "yourAPIkey"

# Create retrieve token function
hatebaseToken <- function(version = NULL, api_key = NULL) { 
  
  # Handshake 
  r <- POST(url = paste0("https://api.hatebase.org/", version, "/authenticate"), 
            body = list(api_key = api_key), 
            encode = "form")
  
  # Retrieve token
  rText <- content(r, as = "text") # extract content 
  token <- fromJSON(rText)$result['token'] %>% # parse text & subset object
    as.character() # character format
  
  return(token)
}

# Run retrieve token function 
token <- hatebaseToken(version = version, api_key = api_key)
```

# Query phase: Get vocabulary 

## Number of pages 

```{r}
# Retrieve page numbers 
hatebaseVocabPages <- function(version = version, token = token) {
  
  # Get vocabulary information 
  r <- POST(url = paste0("https://api.hatebase.org/", version, "/get_vocabulary"), 
            body = list(token = token, format = "json"))
  
  # Total number of pages
  rText <- content(r, "text")
  nPages <- fromJSON(rText)$number_of_pages
  
  return(nPages)
  }

nPages <- hatebaseVocabPages(version = version, token = token)
```

## Get vocabulary from every page

```{r}
# Initialize list
hateList <- vector("list", nPages)

# Input parameters
inputParams <- list(token = token, 
               page = "i", 
               format = "json")

# For loop
for(i in 1:nPages){ 
  hateList[[i]] <- POST(url = paste0("https://api.hatebase.org/", version, "/get_vocabulary"), 
                        body = inputParams) %>%
    httr::content() %>%
    fromJSON() 
  }

```

## Convert from list to data frame 

```{r}
# Convert to data frame
hateDF <- lapply(hateList, '[', 'result') %>%
  map(as.data.frame) %>% 
  data.table::rbindlist()

# Save as csv
write_csv(hateDF, "hateBase.csv")
```



